apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: devops-demo
type: Opaque
stringData:
  DB_USER: "appuser"
  DB_PASSWORD: "super-secret-password"
  # add more secrets here (API keys, tokens, etc.)
