apiVersion: v1
kind: Service
metadata:
  name: backend
  annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "5000"
  prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.backend.serviceType }}
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}