apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  NODE_ENV: "production"
  # Add more configs here, e.g.:
  # API_URL: "http://backend:5000"