apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: {{ .Values.frontend.serviceType }}
  selector:
    app: frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      {{- if and (eq .Values.frontend.serviceType "NodePort") .Values.frontend.nodePort }}
      nodePort: {{ .Values.frontend.nodePort }}
      {{- end }}