apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # Encode values in base64 (echo -n "mypassword" | base64)
  DB_PASSWORD: {{ .Values.backend.dbPassword | b64enc | quote }}
  # Example: add API keys here later if needed